apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-kubernetes-example
  namespace: development
  labels:
    app: express-kubernetes-example
    component: server
    part-of: express-kubernetes-example
    environment: development
    technology: express
    service-type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-kubernetes-example
      environment: development
  strategy: {}
  template:
    metadata:
      labels:
        app: express-kubernetes-example
        component: server
        part-of: express-kubernetes-example
        environment: development
        technology: express
        service-type: backend
    spec:
      containers:
        - image: express-kubernetes-example
          imagePullPolicy: Never
          name: express-kubernetes-example
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 300Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
status: {}
