apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: express-kubernetes-example
  namespace: development
  labels:
    app.kubernetes.io/name: express-kubernetes-example
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: express-kubernetes-example
    my-company.com/environment: development
    my-company.com/technology: express
    my-company.com/owner: albert
  annotations:
    my-company.com/description: Example of an express service working in Kubernetes
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-kubernetes-example
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
