apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: express-kubernetes-example
  namespace: development
  labels:
    app: express-kubernetes-example
    component: server
    part-of: express-kubernetes-example
    environment: development
    technology: express
    service-type: backend
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: express-kubernetes-example
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
