apiVersion: v1
kind: Service
metadata:
  name: express-kubernetes-example
  namespace: development
  labels:
    app.kubernetes.io/name: express-kubernetes-example
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: express-kubernetes-example
    my-company.com/environment: development
    my-company.com/technology: express
    my-company.com/service-type: backend
  annotations:
    my-company.com/owner: albert
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/name: express-kubernetes-example
    my-company.com/environment: development
  type: ClusterIP
status:
  loadBalancer: {}
