extends: default

ignore: |
  node_modules/
  kubernetes/extensions/*

rules:
  document-start:
    present: false
    ignore: |
      kubernetes/*
  line-length:
    ignore: |
      /.github/actions/**/*.yml
      /.github/workflows/*.yml
      /.github/settings.yml
      kubernetes/*
  truthy:
    ignore: |
      /.github/workflows/*.yml
