extends: default

ignore: |
  node_modules/
  kubernetes/hpas/metrics-server/*

rules:
  document-start:
    present: false
  line-length:
    ignore: |
      /.github/actions/**/*.yml
      /.github/workflows/*.yml
      /.github/settings.yml
  truthy:
    ignore: |
      /.github/workflows/*.yml
