apiVersion: v1
kind: Pod
metadata:
  name: express-kubernetes-example
  labels:
    app: express-kubernetes-example
spec:
  containers:
    - image: express-kubernetes-example
      imagePullPolicy: Never
      name: express-kubernetes-example
      ports:
        - containerPort: 3000
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
