apiVersion: v1
kind: Pod
metadata:
  name: express-kubernetes-example
  labels:
    app: express-kubernetes-example
spec:
  containers:
    - image: express-kubernetes-example
      imagePullPolicy: Never
      name: express-kubernetes-example
      ports:
        - containerPort: 3000
          name: http
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 256m
          memory: 300Mi
      livenessProbe:
        httpGet:
          path: /api/health
          port: http
      readinessProbe:
        httpGet:
          path: /api/health
          port: http
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
