apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-kubernetes-example
  labels:
    app: express-kubernetes-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-kubernetes-example
  strategy: {}
  template:
    metadata:
      labels:
        app: express-kubernetes-example
    spec:
      containers:
        - image: express-kubernetes-example
          imagePullPolicy: Never
          name: express-kubernetes-example
          ports:
            - containerPort: 3000
              name: http
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 256m
              memory: 300Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
status: {}
