apiVersion: ENC[AES256_GCM,data:GFA=,iv:tpn1NLaMwg2F+A2i0BDc9maz0PKnvmYm5lmYuHHcPCQ=,tag:7X7V9BpF8ANAPXbiDKw76w==,type:str]
kind: ENC[AES256_GCM,data:7qeiS9W+WkGc,iv:bicT0W3O63KRP4b5N2f1+SVgP+1MdyaG0g5bs8a7xTQ=,tag:YWtAyPiTpB4SgdVaam5Bgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fy6MPR/A4vltEKsllMoyU96M924yHuAAasU=,iv:IkDXFzj66qDftTMHrw6CUJ9ydxevENZgwVvSoWKeves=,tag:egOX5KJpnyz69Yd0TrebSg==,type:str]
    namespace: ENC[AES256_GCM,data:CMEdLVSzUfrfeVI=,iv:wEu0+9y9ftX3XlVa2CHYXfoRKRZVnKthXdX0miDf+m8=,tag:DuaKz1RcARlOMBciPZY3ZQ==,type:str]
    labels:
        app.kubernetes.io/name: ENC[AES256_GCM,data:xxDbGtK6UFzeM7vtrijQhpjVxa8VWTx0yJc=,iv:qyssxrD+3VuanuFBLE8IvUfbZmCmuUewRqbeqdrlS/M=,tag:iNGc4jWg+qch3xfZmGbCTA==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:IdiaDzJr,iv:jwLUpCxjR1iFjcUMOiVVyzJo8Ug+S5bKrOLvaIZikas=,tag:E4Mcu9jgv2UZEhsyZekXfg==,type:str]
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:N6cmQcYcJDaTUBzke6C1bw4SE/3iaVwaRxA=,iv:zi0ZtPwzvrreG+6LNlMpojNdOtUMMJXxXKGTFAG+mEM=,tag:FnCxgNoj+v1mcgVkoCRy9w==,type:str]
        my-company.com/environment: ENC[AES256_GCM,data:Vb7dR9BnPJ0hbMU=,iv:qH648gr2QAeOJPFV6DvAlhPi/VHid6xmoFHCOKa3AlM=,tag:Xtky/6QpoukQTJlBlph6LQ==,type:str]
        my-company.com/technology: ENC[AES256_GCM,data:oiMnBykJ0g==,iv:drAfSEb+9WfUTWYOWOWNNm5luSkHGNTIxCS4TlfQBJc=,tag:TXgDvL9/FNz5tLFqyiN/dA==,type:str]
        my-company.com/owner: ENC[AES256_GCM,data:phnX8uhq,iv:KCxrYAqOM/v3Qjng1DLXzoltUJsui/L5yKm3qxSmBFw=,tag:qEty83aMnyx5/ESBsNLkKQ==,type:str]
data:
    SERVICE_NAME: ENC[AES256_GCM,data:o+kjJSq5UJyIKaPRNvZphI1akM7JXjyEXjk=,iv:S8d6HPlaEcS3FtHt2kjIXRMbF+svRXncc4oUOAGj6sI=,tag:kfECC0Ipg55ZNyzc+Bil0g==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:r9rnBrI3JTmN6g==,iv:KGNi67qi5TYO8j14KpWuESNBVYqgqKEEli13pE1VkP0=,tag:nVmiOCB43HpBJtolyfquAA==,type:str]
    PORT: ENC[AES256_GCM,data:YgC9wA==,iv:KSggcxsgO3Sqa8CcDUrraO4ih/woK+yFS6CqNDbb6H8=,tag:dMOHIJR0wQ1N5Jmj1t3xww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-26T15:52:00Z"
    mac: ENC[AES256_GCM,data:CqKgZIWUb6aMvzNyF/ARGYsrtUiwYzIAaMKms4HCrfW7WNcWnAkqx8iPkWvF9bPho3kbIR9Avnv9Ctf5dx0aWYLcAz3IZRbjTLQFlIE8SLcgzNg80M92iBYlZJQGHoJVXA3LsKSOhJngHv4F1ZF6c3hsYjvT6klu21WkPZjwxe8=,iv:+sU/Kl4M2awC4q+YLYXLXjdv7C5T3n5LUs22ArN4P1E=,tag:aA9hWnxwFZiDrxxIboPRAg==,type:str]
    pgp:
        - created_at: "2024-07-26T15:52:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hIwDXFUltYFwV4MBBACITPFyJLCbmkZpbI5g2Fc7Q58Ka6kRYKNQ36MdtUQG3pfm
            y20lYZauqpQYejweJ43BrHho9LjZPwd2h7OpuRNU5x/+ZyJaMEcfF3nkmLbAok7X
            3fzhjnAJfr/OBhWLbtZBTHycimf6QKVoPEoiZoD1oPnnyPGozmQdq3fDF/K6zdJc
            AY+rSVZ7R8K4RRkCFyz7f0C7BgstJpUEAT07siDH0ALK/D6lKAp5gZn5Q9WaWZDz
            hj9C7rh6Tl1XkOfHeYRAgmnR4txuShRr9qiAYy4OB3DJkAK9GCntNP+64tU=
            =AgyX
            -----END PGP MESSAGE-----
          fp: D7229043384BCC60326C6FB9D8720D957C3D3074
    unencrypted_suffix: _unencrypted
    version: 3.9.0
